services:
  - type: web
    name: feature-store
    env: docker
    dockerfilePath: ./Dockerfile.render
    dockerContext: ./
    healthCheckPath: /health
    plan: free
    envVars:
      - key: POSTGRES_URL
        sync: false
      - key: REDIS_URL
        sync: false  
      - key: API_KEY_SECRET
        generateValue: true
